FROM docker.softgarden.de/sgops/base:9

ENV JDK_VERSION=17 \
    LANG=en_US.UTF-8

# install openjdk-devel
RUN    dnf -y install java-17-openjdk-devel \
    && dnf -y install langpacks-en \
    && dnf clean all

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME /usr/lib/jvm/java


ARG REPOSITORY_REVISION
ARG REPOSITORY_URL
LABEL org.opencontainers.image.authors="Stefan Schueffler <s.schueffler@softgarden.de>"
LABEL org.opencontainers.image.vendor="softgarden e-recruiting GmbH"
LABEL org.opencontainers.image.source=$REPOSITORY_URL
LABEL org.opencontainers.image.revision=$REPOSITORY_REVISION
LABEL org.opencontainers.image.version=17
