FROM docker.softgarden.de/sgops/base:8

ENV JDK_VERSION=11.0.11+9 \
    LANG=en_US.UTF-8

# install AdoptOpenJDK from their official repository
RUN    echo -e "\
[AdoptOpenJDK] \n\
name=AdoptOpenJDK \n\
baseurl=https://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/8/$(uname -m) \n\
enabled=1 \n\
gpgcheck=1 \n\
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public \n\
" > /etc/yum.repos.d/adoptopenjdk.repo \
    && yum -y install adoptopenjdk-11-hotspot-${JDK_VERSION} \
    && yum -y install langpacks-de glibc-all-langpacks \
    && yum clean all

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME /usr/lib/jvm/adoptopenjdk-11-hotspot


ARG REPOSITORY_REVISION
ARG REPOSITORY_URL
LABEL org.opencontainers.image.authors="Stefan Schueffler <s.schueffler@softgarden.de>"
LABEL org.opencontainers.image.vendor="softgarden e-recruiting GmbH"
LABEL org.opencontainers.image.source=$REPOSITORY_URL
LABEL org.opencontainers.image.revision=$REPOSITORY_REVISION
LABEL org.opencontainers.image.version=adoptopenjdk-hotspot-11.0.11
