FROM docker.softgarden.de/sgops/base:9

ENV JDK_VERSION=11 \
    LANG=en_US.UTF-8

# install Adoptium from their official repository
RUN    echo -e "\
[Adoptium] \n\
name=Adoptium \n\
baseurl=https://packages.adoptium.net/artifactory/rpm/rhel/\$releasever/\$basearch \n\
enabled=1 \n\
gpgcheck=1 \n\
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public \n\
" > /etc/yum.repos.d/adoptium.repo \
    && yum -y install temurin-11-jdk \
    && yum -y install langpacks-de glibc-all-langpacks \
&& yum clean all

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME /usr/lib/jvm/temurin-11-jdk


ARG REPOSITORY_REVISION
ARG REPOSITORY_URL
LABEL org.opencontainers.image.authors="Stefan Schueffler <s.schueffler@softgarden.de>"
LABEL org.opencontainers.image.vendor="softgarden e-recruiting GmbH"
LABEL org.opencontainers.image.source=$REPOSITORY_URL
LABEL org.opencontainers.image.revision=$REPOSITORY_REVISION
LABEL org.opencontainers.image.version=adoptium-temurin-11
