FROM centos:8
MAINTAINER Stefan Schueffler <s.schueffler@softgarden.de>

ENV IMAGE_VERSION=adoptopenjdk-openj9-11.0.12

ENV LANG=en_US.UTF-8

# install AdoptOpenJDK from their official repository
RUN    yum -y update \
    && yum install -y https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.12%2B7_openj9-0.27.0/ibm-semeru-open-11-jdk-11.0-12.0.x86_64.rpm \
    && yum -y install langpacks-de glibc-all-langpacks \
    && yum clean all

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME /usr/lib/jvm/ibm-semeru-open-11-jdk
