FROM docker.softgarden.de/sgops/base:8

ENV LANG=en_US.UTF-8

# install IBM Semeru from their official repository
RUN    yum install -y https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.16.1%2B1_openj9-0.33.1/ibm-semeru-open-11-jdk-11.0.16.1.1_0.33.1-1.$(uname -m).rpm \
    && yum -y install langpacks-de glibc-all-langpacks \
    && yum clean all

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME /usr/lib/jvm/ibm-semeru-open-11-jdk


ARG REPOSITORY_REVISION
ARG REPOSITORY_URL
LABEL org.opencontainers.image.authors="Stefan Schueffler <s.schueffler@softgarden.de>"
LABEL org.opencontainers.image.vendor="softgarden e-recruiting GmbH"
LABEL org.opencontainers.image.source=$REPOSITORY_URL
LABEL org.opencontainers.image.revision=$REPOSITORY_REVISION
LABEL org.opencontainers.image.version=ibm-semeru-openj9-11
